version: "3"

services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
      POSTGRES_INITDB_WALDIR: "/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"

volumes:
  postgres-data:
