version: "3"

services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ddigtal
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
